### ISSUE TITLE
The aiforge submit tool may not be the newest version

### ISSUE THREAD

**Issue by zyfdegh** [linkernetworks/environments#26]
There are 2 situations that the submit tool will not be upgraded to latest version.

* The image was built, but a newer version of aiforge is released.
* The installing command is cached by docker builder.

https://github.com/linkernetworks/environments/blob/acd59f5d52907cd134b366bc5d81bb8b32f18701/base/minimal-notebook/Dockerfile#L42

Related Jira issues: 
https://linkernetworks.atlassian.net/browse/AA-82
https://linkernetworks.atlassian.net/browse/ST-1235

**Comment by c9s** [comment]
You can use timestamp in the command to invalid the cache

**Comment by zyfdegh** [comment]
Done, fixing in #27 #28, closing
