### ISSUE TITLE
caffe image building failure

### ISSUE THREAD

**Issue by kkdai** [linkernetworks/environments#39]
`
==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.5.4

Please update conda by running

    $ conda update -n base conda

IsADirectoryError(21, 'Is a directory')

The command '/bin/sh -c conda install --quiet --yes -c anaconda     caffe     python-lmdb &&     conda clean -tipsy &&     fix-permissions $CONDA_DIR' returned a non-zero code: 1
`

**Comment by narumiruna** [comment]
#40
