### ISSUE TITLE
Current make notebook images only one framework version

### ISSUE THREAD

**Issue by kkdai** [linkernetworks/environments#42]
ex: 

- Tensorflow  --> only build 1.3
- Pytorch --> only build 0.3.1

**Comment by kkdai** [comment]
目前由於目錄架構  caffe/1.0/Dockerfile

我已經拆解成  notebook-image-caffe-1.0 來跑..

但是無法在 對應那邊讓他變成  
notebook-image-caffe-1.0: notebook-image-caffe-1.0: env/caffe/1.0/Dockerfile ....

**Comment by c9s** [comment]
Can we do caffe:1.0 and caffe2:2.xx ?

Evan Lin <notifications@github.com>於 2018年5月20日 週日，17:35寫道：

**Comment by c9s** [comment]
Let’s check this issue tomorrow

Yo-An Lin <yoanlin93@gmail.com>於 2018年5月20日 週日，20:45寫道：
